# Generated by Django 6.0.5 on 2026-05-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('HexCode', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Emoji',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Emoji', models.CharField(max_length=10)),
            ],
        ),
    ]
