# Generated by Django 6.0.5 on 2026-05-19 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auxiliary', '0001_initial'),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('TotalQuantity', models.IntegerField(default=0)),
                ('UpiAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('CashAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Completed', models.BooleanField(default=False)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('ColorId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Auxiliary.color')),
                ('EmojiId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Auxiliary.emoji')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField(default=1)),
                ('PriceAtPurchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('OrderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.order')),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
    ]
