# Generated by Django 6.0.5 on 2026-05-19 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_alter_orderitem_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='OrderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderItems', to='Order.order'),
        ),
    ]
