# Generated by Django 6.0.5 on 2026-05-19 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auxiliary', '0001_initial'),
        ('Order', '0003_alter_orderitem_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ColorId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Auxiliary.color'),
        ),
        migrations.AlterField(
            model_name='order',
            name='EmojiId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Auxiliary.emoji'),
        ),
    ]
