# Generated by Django 6.0.4 on 2026-06-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_date', models.DateField(db_index=True)),
                ('raw_material_product', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Material Entry',
                'verbose_name_plural': 'Material Entries',
                'db_table': 'material_entries',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
    ]
