# Generated by Django 6.0.4 on 2026-06-09 23:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialentry',
            options={'ordering': ['-entry_date', '-created_at'], 'verbose_name': 'Material Entry (Legacy)', 'verbose_name_plural': 'Material Entries (Legacy)'},
        ),
        migrations.CreateModel(
            name='MaterialVersion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Version name for identification', max_length=255)),
                ('effective_from_date', models.DateField(db_index=True, help_text='Date from which this version is effective')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this version is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Material Version',
                'verbose_name_plural': 'Material Versions',
                'db_table': 'material_versions',
                'ordering': ['-effective_from_date', '-created_at'],
                'unique_together': {('effective_from_date',)},
            },
        ),
        migrations.CreateModel(
            name='MaterialVersionItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('material_name', models.CharField(help_text='Name of the raw material', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the material', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.ForeignKey(help_text='The version this material belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='material_items', to='Materials.materialversion')),
            ],
            options={
                'verbose_name': 'Material Version Item',
                'verbose_name_plural': 'Material Version Items',
                'db_table': 'material_version_items',
                'ordering': ['material_name'],
                'unique_together': {('version', 'material_name')},
            },
        ),
    ]
