# Generated by Django 6.0.4 on 2026-06-10 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Materials', '0002_alter_materialentry_options_materialversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialversionitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Quantity of the material', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
